### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by myprivacygithub** [XPixelGroup/HYPIR#29]
Traceback (most recent call last):
  File "E:\AI\HYPIR\app.py", line 64, in <module>
    model.init_models()
  File "E:\AI\HYPIR\HYPIR\enhancer\base.py", line 37, in init_models
    self.init_text_models()
  File "E:\AI\HYPIR\HYPIR\enhancer\sd2.py", line 17, in init_text_models
    self.base_model_path, subfolder="text_encoder", torch_dtype=self.weight_dtype).to(self.device)
  File "C:\anaconda3\envs\hypir\lib\site-packages\transformers\modeling_utils.py", line 3162, in to
    return super().to(*args, **kwargs)
  File "C:\anaconda3\envs\hypir\lib\site-packages\torch\nn\modules\module.py", line 1343, in to
    return self._apply(convert)
  File "C:\anaconda3\envs\hypir\lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "C:\anaconda3\envs\hypir\lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "C:\anaconda3\envs\hypir\lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "C:\anaconda3\envs\hypir\lib\site-packages\torch\nn\modules\module.py", line 930, in _apply
    param_applied = fn(param)
  File "C:\anaconda3\envs\hypir\lib\site-packages\torch\nn\modules\module.py", line 1329, in convert
    return t.to(
  File "C:\anaconda3\envs\hypir\lib\site-packages\torch\cuda\__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by vootox** [comment]
This is what worked for me but you should  adjust for your specs:
```
Activate 'hypir' environment
pip uninstall -y torch torchvision torchaudio
conda install -y pytorch pytorch-cuda=12.1 torchvision torchaudio -c pytorch -c nvidia
```

> Cuda 12.1 works perfectly fine with my 12.9 CUDA. However, its torch 2.5.1 instead of 2.6.0

I can fix this by customising the requirements file and for cuda 12.9:
```
--extra-index-url https://download.pytorch.org/whl/cu129
torch==2.6.0
torchvision==0.21.0
torchaudio==2.6.0
```

 But right now I'm happy this was smooth and easy fix.
**My specs:**
- OS Windows
- RTX 3090
- NVIDIA-SMI 577.00
- Driver Version: 577.00
- CUDA Version: 12.9

**Comment by myprivacygithub** [comment]
> This is what worked for me but you should adjust for your specs:
> 
> ```
> Activate 'hypir' environment
> pip uninstall -y torch torchvision torchaudio
> conda install -y pytorch pytorch-cuda=12.1 torchvision torchaudio -c pytorch -c nvidia
> ```
> 
> > Cuda 12.1 works perfectly fine with my 12.9 CUDA. However, its torch 2.5.1 instead of 2.6.0
> 
> I can (or could have) fixed by customising the requirements file and for cuda 12.9:
> 
> ```
> --extra-index-url https://download.pytorch.org/whl/cu129
> torch==2.6.0
> torchvision==0.21.0
> torchaudio==2.6.0
> ```
> 
> But right now I'm happy this was smooth and easy fix. **My specs:**
> 
> * OS Windows
> * RTX 3090
> * NVIDIA-SMI 577.00
> * Driver Version: 577.00
> * CUDA Version: 12.9

Thanks. This is solved my promblem.
