### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by cgcgcg-xs** [XPixelGroup/HYPIR#8]
(hypir) D:\py\HYPIR>python app.py --config configs/sd2_gradio.yaml --local --device cuda
Traceback (most recent call last):
  File "D:\py\HYPIR\app.py", line 64, in <module>
    model.init_models()
  File "D:\py\HYPIR\HYPIR\enhancer\base.py", line 37, in init_models
    self.init_text_models()
  File "D:\py\HYPIR\HYPIR\enhancer\sd2.py", line 17, in init_text_models
    self.base_model_path, subfolder="text_encoder", torch_dtype=self.weight_dtype).to(self.device)
  File "E:\miniforge3\envs\hypir\lib\site-packages\transformers\modeling_utils.py", line 3162, in to
    return super().to(*args, **kwargs)
  File "E:\miniforge3\envs\hypir\lib\site-packages\torch\nn\modules\module.py", line 1343, in to
    return self._apply(convert)
  File "E:\miniforge3\envs\hypir\lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "E:\miniforge3\envs\hypir\lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "E:\miniforge3\envs\hypir\lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "E:\miniforge3\envs\hypir\lib\site-packages\torch\nn\modules\module.py", line 930, in _apply
    param_applied = fn(param)
  File "E:\miniforge3\envs\hypir\lib\site-packages\torch\nn\modules\module.py", line 1329, in convert
    return t.to(
  File "E:\miniforge3\envs\hypir\lib\site-packages\torch\cuda\__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by 0x3f3f3f3fun** [comment]
Please follow https://pytorch.org/get-started/previous-versions/ to install torch2.6.0 with cuda support.

or:
```shell
pip uninstall torch torchvision
pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple -r requirements.txt
```

**Comment by cgcgcg-xs** [comment]
Thank you. The problem has been solved.
（Switch to CUDA 12.6 and then reinstall PyTorch.）
